apiVersion: v1
kind: Service
metadata:
  name: pollution-api-service
  labels:
    app.kubernetes.io/name: pollution-api-service
    {{- include "apt.commonLabels" . | nindent 4 }}
spec:
  type: {{ .Values.apiService.service.type }}
  selector:
    app.kubernetes.io/name: pollution-api-service
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.apiService.service.port }}
      targetPort: http
